version: "3.8"
services:
  frontend:
    image: my-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    image: my-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: template
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-template
    ports:
      - "6379:6379"
